### ISSUE TITLE
ember-google-maps on ios webview

### ISSUE THREAD

**Issue by ryanholte** [sandydoo/ember-google-maps#84]
Just wanted to log an issue for any near-term future people trying to use google maps in a ios webview. I ran into an issue where the view would go "brown" or blank. I ended up adding the following css rule:

```css
.ember-google-map {
   -webkit-transform: rotate(0deg);
}
``` 

This solution was mentioned in this issue:
https://github.com/ionic-team/ionic-native-google-maps/issues/213#issuecomment-490021270

🍻
